# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 2.11.0
kubeVersion: ">=1.26.0-0"
name: ntfy
version: 0.2.1
description: ntfy lets you send push notifications to your phone or desktop via scripts from any computer, using simple HTTP PUT or POST requests
home: https://github.com/binwiederhier/ntfy
icon: https://raw.githubusercontent.com/binwiederhier/ntfy/9d3fc20e583564e40af5afb90233f4714fdfcb4c/web/public/static/images/pwa-512x512.png
keywords:
  - pubsub
  - messaging
  - notification
  - desktop
  - mobile
  - ntfy
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJ Studios Helm Authors
    email: info@fmj.studio
  - name: FMJdev
    email: info@fmj.dev
annotations:
  artifacthub.io/category: streaming-messaging
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: ntfy
      image: docker.io/binwiederhier/ntfy:v2.11.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Support
      url: https://github.com/fmjstudios/helm/issues
    - name: ntfy GitHub Repository
      url: https://github.com/binwiederhier/ntfy
    - name: ntfy Documentation
      url: https://docs.ntfy.sh/
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |
    - kind: fixed
      description: add missing namespace references
    - kind: added
      description: volumes and volumeMounts configuration within values.yaml
    - kind: changed
      description: updated values.schema.json