{{- if eq .Values.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "activepieces.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
spec:
  {{ include "activepieces.podSpec" . | nindent 2 }}
{{- end }}