{{- /*
  Encryption secret
*/}}
{{- if not .Values.activepieces.encryption.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activepieces.secrets.encryption" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: activepieces
    {{- include "activepieces.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  connection: {{ default .Values.activepieces.encryption.connection (randAlphaNum 32) | b64enc | quote }}
  jwt: {{ default .Values.activepieces.encryption.jwt (randAlphaNum 32) | b64enc | quote }}
{{- end }}
---
{{- /*
  Queue secret
*/}}
{{- if not .Values.activepieces.queue.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activepieces.secrets.queue" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: activepieces
    {{- include "activepieces.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: "kubernetes.io/basic-auth"
data:
  username: {{ default "admin" .Values.activepieces.queue.username | b64enc | quote }}
  password: {{ default .Values.activepieces.queue.password (randAlphaNum 32) | b64enc | quote }}
{{- end }}
---
{{- /*
  PostgreSQL secret
*/}}
{{- if not .Values.activepieces.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activepieces.secrets.postgresql" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: activepieces
    {{- include "activepieces.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: "kubernetes.io/basic-auth"
data:
  username: {{ default "activepieces" .Values.activepieces.postgresql.username | b64enc | quote }}
  password: {{ default (randAlphaNum 32) .Values.activepieces.postgresql.password | b64enc | quote }}
{{- end }}
---
{{- /*
  Redis secret
*/}}
{{- if not .Values.activepieces.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activepieces.secrets.redis" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: activepieces
    {{- include "activepieces.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: "kubernetes.io/basic-auth"
data:
  {{- if .Values.activepieces.redis.username }}
  username: {{ default "redis" .Values.activepieces.redis.username | b64enc | quote }}
  {{- end }}
  password: {{ default (randAlphaNum 32) .Values.activepieces.redis.password | b64enc | quote }}
{{- end }}
---
{{- /*
  OpenAI secret
*/}}
{{- if not .Values.activepieces.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activepieces.secrets.openai" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: activepieces
    {{- include "activepieces.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  apiKey: {{ .Values.activepieces.copilot.openAI.apiKey | b64enc | quote }}
{{- end }}