apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.pvc.name" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ $.Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace | quote }}
    {{- if (eq .Values.vaultwarden.data.pvc.reclaimPolicy "Retain") }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  storageClassName: {{ .Values.vaultwarden.data.pvc.storageClass | default "standard" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vaultwarden.data.pvc.size }}