{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: {{ include "gobackup.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "gobackup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gobackup.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gobackup.selectorLabels" . | nindent 6 }}
{{- end }}