apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkstack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: linkstack
    {{- include "linkstack.labels" . | nindent 4 }}
    {{- if .Values.configMap.labels }}
    {{- toYaml .Values.configMap.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.configMap.annotations }}
  annotations:
  {{- toYaml .Values.configMap.annotations | nindent 4 }}
  {{- end }}
data:
  SERVER_ADMIN: {{ .Values.linkstack.serverAdmin }}
  LOG_LEVEL: {{ .Values.linkstack.logLevel }}
  TZ: {{ .Values.linkstack.timeZone }}
  PHP_MEMORY_LIMIT: {{ .Values.linkstack.phpMemoryLimit }}
  UPLOAD_MAX_FILESIZE: {{ .Values.linkstack.uploadMaxFileSize }}
  {{- if .Values.linkstack.serverName }}
  HTTP_SERVER_NAME: {{ .Values.linkstack.serverName }}
  HTTPS_SERVER_NAME: {{ .Values.linkstack.serverName }}
  {{ end }}