apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubenav.secret.saToken" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kubenav
    {{- include "kubenav.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  annotations:
    kubernetes.io/service-account.name: {{ include "kubenav.serviceAccountName" . | quote }}
  {{- if .Values.secret.annotations }}
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: kubernetes.io/service-account-token