# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
kubeVersion: ">=1.26"
name: kubenav
version: 0.1.0
description: "kubenav is the navigator for your Kubernetes clusters in your pocket: a mobile app to manage clusters and get an overview of the status of your resources"
home: https://kubenav.io/
icon: https://raw.githubusercontent.com/kubenav/kubenav/290f1776b03c359b8115125fa37a4b8dd73b6464/utils/images/app-icons/android.png
keywords:
  - dashboard
  - android
  - ios
  - mobile
  - kubeconfig
  - rbac
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJ Studios Helm Authors
    email: info@fmj.studio
  - name: FMJdev
    email: info@fmj.dev
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Support
      url: https://github.com/fmjstudios/helm/issues
    - name: Kubenav Homepage
      url: https://kubenav.io/
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/