{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gotenberg.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gotenberg.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.secrets -}}
  secrets:
    {{- toYaml .Values.serviceAccount.secrets | nindent 4 }}
  {{- end }}
{{- end }}
