# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 1.30.5
kubeVersion: ">=1.26"
name: vaultwarden
version: 0.1.2
description: Vaultwarden is an open-source, community-supported, Bitwarden-comptabile server written in Rust
home: https://github.com/dani-garcia/vaultwarden
icon: https://raw.githubusercontent.com/fmjstudios/artwork/2fd182517d56ffeee59f82ec75b651e92344d151/projects/vaultwarden/icon/black/vaultwarden-icon-black.png
keywords:
  - passwords
  - password-manager
  - bitwarden
  - keepass
  - vaultwarden
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJ Studios Helm Authors
    email: info@fmj.studio
  - name: FMJdev
    email: info@fmj.dev
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: vaultwarden
      image: docker.io/vaultwarden/server:1.30.5-alpine
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Support
      url: https://github.com/fmjstudios/helm/issues
    - name: Vaultwarden GitHub Repository
      url: https://github.com/dani-garcia/vaultwarden
    - name: Vaultwarden Documentation
      url: https://github.com/dani-garcia/vaultwarden/wiki
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |
    - kind: added
      description: Support links via annotations
    - kind: added
      description: Verified chart publisher
    - kind: removed
      description: obsolete (duplicated) annotations