# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 0.28.0
kubeVersion: ">=1.26.0-0"
name: activepieces
version: 0.2.1
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    version: ~15.5
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
    version: ~19.5
description: Activepieces is an open source all-in-one automation tool with 100+ integrations
home: https://www.activepieces.com/
icon: https://raw.githubusercontent.com/fmjstudios/artwork/3f3537b0377b8c95bfac77ae5cb7779c4698d659/projects/activepieces/icon/color/activepieces-icon-color.png
keywords:
  - automation
  - workflow
  - activepieces
  - zapier
  - n8n
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJ Studios Helm Authors
    email: info@fmj.studio
  - name: FMJdev
    email: info@fmj.dev
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: gobackup
      image: docker.io/activepieces/activepieces:0.28.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Support
      url: https://github.com/fmjstudios/helm/issues
    - name: Activepieces Homepage
      url: https://www.activepieces.com/
    - name: Activepieces Documentation
      url: https://www.activepieces.com/docs/getting-started/introduction
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/