name: 'Run Super-Linter'

on: ['push', 'pull_request']

jobs:
  lint:
    name: Super-Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Superlinter
        uses: super-linter/super-linter@v6.6.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASH_EXEC_IGNORE_LIBRARIES: true
          # mostly false positives
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_JSCPD: false
          VALIDATE_KUBERNETES_KUBECONFORM: false
          # cannot handle Helm templates
          VALIDATE_YAML: false
          # random issues
          VALIDATE_CHECKOV: false
